name: Any Branch PR Test Workflow

on: [push]
jobs:
  job_1:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [11.14.0]
    steps:
      - name: Checkout PR branch branch
        uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: NPM install
        run: |
          npm install
      - name: NPM test
        run: |
          npm test
        env:
          CI: true
