name: Develop Deployment Workflow

on:
  push:
    branches:
      - develop
jobs:
  job_1:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [11.14.0]
    steps:
      - name: Checkout pushed branch
        uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: NPM install
        run: |
          npm install
      - name: NPM test
        run: |
          npm test
        env:
          CI: true
  job_2:
    needs: job_1
    name: Create tag
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: develop
    - name: Bump version and push tag
      id: step_tag
      uses: anothrNick/github-tag-action@output-tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: 'patch'
        WITH_V: true
    - name: Get the version of tag
      id: get_version
      run: |
        echo ${{steps.step_tag.outputs.new_tag}}
